from uuid import UUID
from datetime import timedelta
from .models import RiskIndicator, Thresholds

SAMPLE_INDICATORS = [
    RiskIndicator(
        id=UUID('11111111-1111-1111-1111-111111111111'),
        name='System Availability',
        category='Operational Risk',
        description='Percentage of time the system is available',
        calculation_method='raw_percentage',
        data_sources=['monitoring'],
        thresholds=Thresholds(low=90, medium=95, high=99, critical=99.9),
        weight=0.2,
        update_frequency=timedelta(minutes=5),
        owner='ops-team',
    ),
    RiskIndicator(
        id=UUID('22222222-2222-2222-2222-222222222222'),
        name='Revenue Variance',
        category='Financial Risk',
        description='Difference between expected and actual revenue',
        calculation_method='percentage_variance',
        data_sources=['finance-system'],
        thresholds=Thresholds(low=5, medium=10, high=20, critical=30),
        weight=0.3,
        update_frequency=timedelta(hours=1),
        owner='finance-team',
    ),
    RiskIndicator(
        id=UUID('33333333-3333-3333-3333-333333333333'),
        name='Regulatory Violations',
        category='Compliance Risk',
        description='Count of regulatory breaches per quarter',
        calculation_method='count',
        data_sources=['compliance-db'],
        thresholds=Thresholds(low=1, medium=3, high=5, critical=8),
        weight=0.1,
        update_frequency=timedelta(days=1),
        owner='compliance-team',
    ),
    RiskIndicator(
        id=UUID('44444444-4444-4444-4444-444444444444'),
        name='Unauthorized Access Attempts',
        category='Security Risk',
        description='Number of failed login attempts per hour',
        calculation_method='count',
        data_sources=['auth-log'],
        thresholds=Thresholds(low=10, medium=50, high=100, critical=200),
        weight=0.15,
        update_frequency=timedelta(minutes=15),
        owner='security-team',
    ),
    RiskIndicator(
        id=UUID('55555555-5555-5555-5555-555555555555'),
        name='Customer Complaints',
        category='Reputational Risk',
        description='Monthly count of official complaints',
        calculation_method='count',
        data_sources=['support-system'],
        thresholds=Thresholds(low=5, medium=20, high=50, critical=100),
        weight=0.15,
        update_frequency=timedelta(days=1),
        owner='customer-success',
    ),
    RiskIndicator(
        id=UUID('66666666-6666-6666-6666-666666666666'),
        name='Market Share Changes',
        category='Strategic Risk',
        description='Quarter over quarter market share delta',
        calculation_method='percentage_variance',
        data_sources=['market-research'],
        thresholds=Thresholds(low=1, medium=3, high=5, critical=8),
        weight=0.1,
        update_frequency=timedelta(days=30),
        owner='strategy-team',
    ),
]
